apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config

data:
  redis.conf: |
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /var/lib/redis/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
    dir /var/lib/redis
    port 6379
  sentinel.conf: |
    # Host and port we will listen for requests on
    #bind 127.0.0.1
    port 16379
    #
    # "redis-cluster" is the name of our cluster
    #
    # each sentinel process is paired with a redis-server process
    #
    sentinel monitor redis-cluster 0.0.0.0 6379 2
    sentinel down-after-milliseconds redis-cluster 5000
    sentinel failover-timeout redis-cluster 10000

