apiVersion: v1
kind: ImageStream
metadata:
  name: redis-base
spec:
  imagePullPolicy: IfNotPresent
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: 'docker.io/redis:3.2.0-alpine'
    name: latest
    referencePolicy:
      type: "Local"

---
apiVersion: v1
kind: ImageStream
metadata:
  name: redis-nextcloud
---

apiVersion: v1
kind: BuildConfig
metadata:
  name: "redis-build-base"
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "redis-nextcloud:latest"
  source:
    git:
      uri: http://github.com/project616/redis-cluster-okd.git
      ref: "master"
  images:
  - from:
      kind: "ImageStreamTag"
      name: "redis-nextcloud:latest"
  runPolicy: "Serial"
  strategy:
    dockerStrategy:
      noCache: true
      from:
        kind: "ImageStreamTag"
        name: "redis-base:latest"
  triggers:
    - type: "ImageChange"
    - type: "ConfigChange"
